# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hamza/github/simple-photo-editor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hamza/github/simple-photo-editor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hamza/github/simple-photo-editor/CMakeFiles /home/hamza/github/simple-photo-editor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hamza/github/simple-photo-editor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple-image-editor

# Build rule for target.
simple-image-editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-image-editor
.PHONY : simple-image-editor

# fast build rule for target.
simple-image-editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/build
.PHONY : simple-image-editor/fast

src/App.o: src/App.cpp.o
.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i
.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s
.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/Controllers/AdjustmentTypesConverter.o: src/Controllers/AdjustmentTypesConverter.cpp.o
.PHONY : src/Controllers/AdjustmentTypesConverter.o

# target to build an object file
src/Controllers/AdjustmentTypesConverter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/AdjustmentTypesConverter.cpp.o
.PHONY : src/Controllers/AdjustmentTypesConverter.cpp.o

src/Controllers/AdjustmentTypesConverter.i: src/Controllers/AdjustmentTypesConverter.cpp.i
.PHONY : src/Controllers/AdjustmentTypesConverter.i

# target to preprocess a source file
src/Controllers/AdjustmentTypesConverter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/AdjustmentTypesConverter.cpp.i
.PHONY : src/Controllers/AdjustmentTypesConverter.cpp.i

src/Controllers/AdjustmentTypesConverter.s: src/Controllers/AdjustmentTypesConverter.cpp.s
.PHONY : src/Controllers/AdjustmentTypesConverter.s

# target to generate assembly for a file
src/Controllers/AdjustmentTypesConverter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/AdjustmentTypesConverter.cpp.s
.PHONY : src/Controllers/AdjustmentTypesConverter.cpp.s

src/Controllers/ImageAdjustmentPanel.o: src/Controllers/ImageAdjustmentPanel.cpp.o
.PHONY : src/Controllers/ImageAdjustmentPanel.o

# target to build an object file
src/Controllers/ImageAdjustmentPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/ImageAdjustmentPanel.cpp.o
.PHONY : src/Controllers/ImageAdjustmentPanel.cpp.o

src/Controllers/ImageAdjustmentPanel.i: src/Controllers/ImageAdjustmentPanel.cpp.i
.PHONY : src/Controllers/ImageAdjustmentPanel.i

# target to preprocess a source file
src/Controllers/ImageAdjustmentPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/ImageAdjustmentPanel.cpp.i
.PHONY : src/Controllers/ImageAdjustmentPanel.cpp.i

src/Controllers/ImageAdjustmentPanel.s: src/Controllers/ImageAdjustmentPanel.cpp.s
.PHONY : src/Controllers/ImageAdjustmentPanel.s

# target to generate assembly for a file
src/Controllers/ImageAdjustmentPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/ImageAdjustmentPanel.cpp.s
.PHONY : src/Controllers/ImageAdjustmentPanel.cpp.s

src/Controllers/ImageAdjustmentsEvent.o: src/Controllers/ImageAdjustmentsEvent.cpp.o
.PHONY : src/Controllers/ImageAdjustmentsEvent.o

# target to build an object file
src/Controllers/ImageAdjustmentsEvent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/ImageAdjustmentsEvent.cpp.o
.PHONY : src/Controllers/ImageAdjustmentsEvent.cpp.o

src/Controllers/ImageAdjustmentsEvent.i: src/Controllers/ImageAdjustmentsEvent.cpp.i
.PHONY : src/Controllers/ImageAdjustmentsEvent.i

# target to preprocess a source file
src/Controllers/ImageAdjustmentsEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/ImageAdjustmentsEvent.cpp.i
.PHONY : src/Controllers/ImageAdjustmentsEvent.cpp.i

src/Controllers/ImageAdjustmentsEvent.s: src/Controllers/ImageAdjustmentsEvent.cpp.s
.PHONY : src/Controllers/ImageAdjustmentsEvent.s

# target to generate assembly for a file
src/Controllers/ImageAdjustmentsEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/ImageAdjustmentsEvent.cpp.s
.PHONY : src/Controllers/ImageAdjustmentsEvent.cpp.s

src/Controllers/MainFrame.o: src/Controllers/MainFrame.cpp.o
.PHONY : src/Controllers/MainFrame.o

# target to build an object file
src/Controllers/MainFrame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/MainFrame.cpp.o
.PHONY : src/Controllers/MainFrame.cpp.o

src/Controllers/MainFrame.i: src/Controllers/MainFrame.cpp.i
.PHONY : src/Controllers/MainFrame.i

# target to preprocess a source file
src/Controllers/MainFrame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/MainFrame.cpp.i
.PHONY : src/Controllers/MainFrame.cpp.i

src/Controllers/MainFrame.s: src/Controllers/MainFrame.cpp.s
.PHONY : src/Controllers/MainFrame.s

# target to generate assembly for a file
src/Controllers/MainFrame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple-image-editor.dir/build.make CMakeFiles/simple-image-editor.dir/src/Controllers/MainFrame.cpp.s
.PHONY : src/Controllers/MainFrame.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simple-image-editor"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/Controllers/AdjustmentTypesConverter.o"
	@echo "... src/Controllers/AdjustmentTypesConverter.i"
	@echo "... src/Controllers/AdjustmentTypesConverter.s"
	@echo "... src/Controllers/ImageAdjustmentPanel.o"
	@echo "... src/Controllers/ImageAdjustmentPanel.i"
	@echo "... src/Controllers/ImageAdjustmentPanel.s"
	@echo "... src/Controllers/ImageAdjustmentsEvent.o"
	@echo "... src/Controllers/ImageAdjustmentsEvent.i"
	@echo "... src/Controllers/ImageAdjustmentsEvent.s"
	@echo "... src/Controllers/MainFrame.o"
	@echo "... src/Controllers/MainFrame.i"
	@echo "... src/Controllers/MainFrame.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

